name: music
description: A Music app to play local audio files.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  audiotagger: ^2.2.1
  bloc: ^8.0.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.0.3
  on_audio_query: ^2.5.3+1
  permission_handler: ^8.3.0
  shared_preferences: ^2.0.12

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - asset/images/

  fonts:
    - family: IconFont
      fonts:
        - asset: asset/fonts/Icon-Font.ttf
    - family: Poppins
      fonts:
        - asset: asset/fonts/Poppins-Light.ttf
          weight: 200
        - asset: asset/fonts/Poppins-Thin.ttf
          weight: 300
        - asset: asset/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: asset/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: asset/fonts/Poppins-SemiBold.ttf
          weight: 600
